### ISSUE TITLE
Provide option to use double quotes

### ISSUE THREAD

**Issue by johnnybubonic** [alessio/shellescape#15]
In the event that it is desired that variables be parsed by the shell in the resulting string of e.g. .Quote() but it is otherwise escaped/sanitized, an additional set of functions should be provided to wrap in double-quotes instead of single-quotes etc.

**Comment by alessio** [comment]
I like this idea. Could you provide a few test cases, please?

**Comment by alessio** [comment]
Needs more details. Closing for now.
